spring:
  datasource:
    password: Epiousion10!
    url: jdbc:mysql://localhost:3306/jwtsecurity
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8080
  servlet:
    context-path: /poc
